---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: generic-resource
  namespace: proxy-lg
rules:
  - apiGroups:
      - "rtcfg.dvext.io"
    resources:
      - "generic"
    verbs:
      - "*"
  - apiGroups: #To be able to read self pod labels
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: generic-rs-role-binding
  namespace: proxy-lg
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: generic-resource
subjects:
  - kind: ServiceAccount
    name: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: generic-resource
  namespace: proxy-lg
rules:
  - apiGroups:
      - 'rtcfg.dvext.io'
    resources:
      - 'generic'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: generic-rs-role-binding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: proxy-lg